# Generated by Django 4.1.5 on 2023-10-28 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=100)),
                ('photo_medium_url', models.URLField()),
                ('photo_large_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(max_length=100)),
                ('activity_type', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('distance', models.IntegerField()),
                ('activity_athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StravaChallengesApp.athlete')),
            ],
        ),
    ]
