# Generated by Django 4.1.5 on 2023-11-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaChallengesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_athlete',
            field=models.CharField(max_length=100),
        ),
    ]
