# Generated by Django 4.1.5 on 2023-11-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaChallengesApp', '0002_alter_activity_activity_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='other_ytd_distance',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='athlete',
            name='ride_ytd_distance',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='athlete',
            name='run_ytd_distance',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='athlete',
            name='ski_ytd_distance',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='athlete',
            name='swim_ytd_distance',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='athlete',
            name='total_ytd_distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athlete',
            name='walk_ytd_distance',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='username',
            field=models.CharField(default='Brak', max_length=100),
        ),
    ]
