# Generated by Django 4.1.5 on 2023-11-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StravaChallengesApp', '0003_athlete_last_modified_athlete_other_ytd_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='other_ytd_distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='ride_ytd_distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='run_ytd_distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='ski_ytd_distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='swim_ytd_distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='walk_ytd_distance',
            field=models.IntegerField(default=0),
        ),
    ]
